### ISSUE TITLE
Bug in CurrencyInputFormatter

### ISSUE THREAD

**Issue by alex9153** [caseyryan/flutter_multi_formatter#92]
`CurrencyInputFormatter(thousandSeparator: ThousandSeparator.Space, mantissaLength: 0, trailingSymbol: " $")`

mantissaLength is 0 and if I tap on dot TextField stops reaction on any typing.

**Comment by caseyryan** [comment]
Thanks. I'll check it

**Comment by caseyryan** [comment]
I could not reproduce this (maybe because of a difference environment) but I've found out that it throws an "out of range exception" in this code when I press period at the end of the line:
```dart 
return oldValue.copyWith(
        selection: TextSelection.collapsed(
          offset: oldCaretIndex + 1,
        ),
      );
```
Maybe it was the reason of the bug you've described.

So I've replaced the code with this
```dart 
return oldValue.copyWith(
        selection: TextSelection.collapsed(
          offset: min(
            oldValue.text.length,
            oldCaretIndex + 1,
          ),
        ),
      );
```
And the exception has gone
